### ISSUE TITLE
clang-cl isn't working with meson - 

### ISSUE THREAD

**Issue by andyfaff** [conda-forge/meson-feedstock#70]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I'm having issues using the `compilers` package with `meson`. I'm interested in using the clang-cl C compiler to build a project. However things aren't quite working.

```
conda create -n test
conda activate test
conda install -c conda-forge compilers python=3.10 meson
mkdir meson-test
cd meson-test
meson init
set CC=clang-cl
set CXX=clang-cl

:: the following line successfully compiles meson_test.exe
%CC% meson_test.c

:: now let's try a meson build
meson build
```

Unfortunately this fails with:

```
(test) H:\programming\meson-test>meson build
The Meson build system
Version: 0.63.1
Source dir: \\filer\home\anz\programming\meson-test
Build dir: \\filer\home\anz\programming\meson-test\build
Build type: native build
Project name: meson-test
Project version: 0.1
Traceback (most recent call last):
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\mesonmain.py", line 153, in run
    return options.run_func(options)
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\msetup.py", line 303, in run
    app.generate()
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\msetup.py", line 186, in generate
    self._generate(env)
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\msetup.py", line 208, in _generate
    intr = interpreter.Interpreter(b, user_defined_options=user_defined_options)
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 344, in __init__
    self.parse_project()
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 119, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 174, in evaluate_codeblock
    raise e
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 167, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 180, in evaluate_statement
    return self.function_call(cur)
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\interpreterbase\interpreterbase.py", line 462, in function_call
    res = func(node, func_args, kwargs)
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 277, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\interpreterbase\decorators.py", line 580, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1257, in func_project
    self.add_languages(proj_langs, True, MachineChoice.HOST)
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1393, in add_languages
    success = self.add_languages_for(args, required, for_machine)
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\interpreter\interpreter.py", line 1431, in add_languages_for
    comp = compilers.detect_compiler_for(self.environment, lang, for_machine)
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\compilers\detect.py", line 225, in detect_compiler_for
    comp = compiler_from_language(env, lang, for_machine)
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\compilers\detect.py", line 222, in compiler_from_language
    return lang_map[lang](env, for_machine) if lang in lang_map else None
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\compilers\detect.py", line 670, in detect_c_compiler
    return _detect_c_or_cpp_compiler(env, 'c', for_machine)
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\compilers\detect.py", line 533, in _detect_c_or_cpp_compiler
    linker = guess_win_linker(env, ['lld-link'], cls, version, for_machine)
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\linkers\detect.py", line 85, in guess_win_linker
    p, o, _ = Popen_safe(compiler + check_args)
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\mesonlib\universal.py", line 1409, in Popen_safe
    p, o, e = Popen_safe_legacy(args, write=write, stdin=stdin, stdout=stdout, stderr=stderr, **kwargs)
  File "C:\Users\anz\Miniconda3\envs\test\lib\site-packages\mesonbuild\mesonlib\universal.py", line 1426, in Popen_safe_legacy
    p = subprocess.Popen(args, universal_newlines=False, close_fds=False,
  File "C:\Users\anz\Miniconda3\envs\test\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\anz\Miniconda3\envs\test\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

ERROR: Unhandled python exception
The system cannot find the file specified - (2, 'The system cannot find the file specified', None, 2, None)
this is probably not a Meson bug.
```
If I then try with MSVC (I'm running this in a VS2019 command prompt) the build works:

```
(test) H:\programming\meson-test> set CC=
(test) H:\programming\meson-test> set CXX=
(test) H:\programming\meson-test>meson build
The Meson build system
Version: 0.63.1
Source dir: \\filer\home\anz\programming\meson-test
Build dir: \\filer\home\anz\programming\meson-test\build
Build type: native build
Project name: meson-test
Project version: 0.1
C compiler for the host machine: cl (msvc 19.16.27048 "Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27048 for x64")
C linker for the host machine: link link 14.16.27048.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Build targets in project: 1

Found ninja-1.11.0 at C:\Users\anz\Miniconda3\envs\test\Library\bin\ninja.EXE
```

I'm not sure where to file this bug, should it be here, or in the `compilers` feedstock, or at the `meson` project?

### Installed packages

```shell
(test) H:\programming>conda list
# packages in environment at C:\Users\anz\Miniconda3\envs\test:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h8ffe710_4    conda-forge
c-compiler                1.5.0                h8ffe710_0    conda-forge
ca-certificates           2022.6.15            h5b45459_0    conda-forge
clangdev                  5.0.0                   flang_3  [flang]  conda-forge
compilers                 1.5.0                h57928b3_0    conda-forge
cxx-compiler              1.5.0                h2d74725_0    conda-forge
flang                     5.0.0           he025d50_20180525    conda-forge
flang_win-64              5.0.0           h13ae965_20180526    conda-forge
fortran-compiler          1.5.0                h9655429_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libflang                  5.0.0           h6538335_20180525    conda-forge
libsqlite                 3.39.2               h8ffe710_1    conda-forge
libzlib                   1.2.12               h8ffe710_2    conda-forge
llvm-meta                 5.0.0                         0    conda-forge
meson                     0.63.1             pyhd8ed1ab_0    conda-forge
ninja                     1.11.0               h2d74725_0    conda-forge
openmp                    5.0.0                    vc14_1    conda-forge
openssl                   3.0.5                h8ffe710_1    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
python                    3.10.6          hcf16a7b_0_cpython    conda-forge
setuptools                65.3.0             pyhd8ed1ab_1    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tzdata                    2022c                h191b570_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
vs2017_win-64             19.16.27033          hb90652a_6    conda-forge
vswhere                   3.0.3                h57928b3_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
```

### Environment info

```shell
(test) H:\programming>conda info

     active environment : test
    active env location : C:\Users\anz\Miniconda3\envs\test
            shell level : 2
       user config file : C:\Users\anz\.condarc
 populated config files : C:\Users\anz\.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.1.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\anz\Miniconda3  (writable)
      conda av data dir : C:\Users\anz\Miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\anz\Miniconda3\pkgs
                          C:\Users\anz\.conda\pkgs
                          C:\Users\anz\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\anz\Miniconda3\envs
                          C:\Users\anz\.conda\envs
                          C:\Users\anz\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.1 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by tschoonj** [comment]
Not sure what that clangdev package is but it doesn't seem to provide clang-cl. Try replacing it with 'clang' in your list of dependencies and it should be available then.

**Comment by andyfaff** [comment]
I know that `clang-cl` is available in the conda env once I've installed the `compilers` package because I can type `clang-cl meson_test.c` and it will make an executable:

```
set CC=clang-cl
set CXX=clang-cl

:: the following line successfully compiles meson_test.exe
%CC% meson_test.c
```

**Comment by tschoonj** [comment]
Having a closer look at the backtrace, it appears that `lld-link` is missing in your environment. Can you confirm this?

**Comment by andyfaff** [comment]
There is no `lld-link` in the environment:
```
(tb) H:\programming\scipy>where lld-link
INFO: Could not find files for the given pattern(s).
```

**Comment by andyfaff** [comment]
I got a bit further:
```
conda create -n test
conda activate test
conda install -y cmake flang clangdev perl libflang ninja lld==11 python meson
```
I then tried `conda install lld`. Installing version 14 didn't work, but `conda install lld==1` *did* work. Now when I try to use meson to build the scipy project I can get as far as figuring out the fortran compiler step, but there's also a linker problem there. Is there a specific conda package I have to install to link the output from `flang`, or is this an issue with meson?

```
(test) H:\programming\scipy>meson build
The Meson build system
Version: 0.63.1
Source dir: \\filer\home\anz\programming\scipy
Build dir: \\filer\home\anz\programming\scipy\build
Build type: native build
Project name: SciPy
Project version: 1.10.0.dev0
C compiler for the host machine: clang-cl (clang-cl 11.0.1)
C linker for the host machine: lld-link lld-link 11.0.0
C++ compiler for the host machine: clang-cl (clang-cl 11.0.1)
C++ linker for the host machine: lld-link lld-link 11.0.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wno-unused-but-set-variable: NO
Library m found: NO

\\filer\home\anz\programming\scipy\meson.build:54:0: ERROR: Unable to detect linker for compiler `flang -Wl,--version`
stdout:
stderr: flang: error: no input files
```

conda list:
```
# packages in environment at C:\Users\anz\Miniconda3\envs\test:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.6.15            h5b45459_0    conda-forge
clang                     11.0.1               h57928b3_1    conda-forge
clang-11                  11.0.1          default_h5c34c98_1    conda-forge
clang-tools               11.0.1          default_h5c34c98_1    conda-forge
clangdev                  11.0.1          default_h5c34c98_1    conda-forge
clangxx                   11.0.1          default_h5c34c98_1    conda-forge
cmake                     3.24.1               h39d44d4_0    conda-forge
flang                     11.0.1          h0e60522_20210131    conda-forge
libclang                  11.0.1          default_h5c34c98_1    conda-forge
libclang-cpp              11.0.1          default_h5c34c98_1    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libflang                  11.0.1          h0e60522_20210131    conda-forge
libllvm11                 11.0.1               hab3b255_0    conda-forge
libsqlite                 3.39.2               h8ffe710_1    conda-forge
libzlib                   1.2.12               h8ffe710_2    conda-forge
lld                       11.0.0               h39d44d4_0    conda-forge
llvm-openmp               11.0.1               h2d74725_0    conda-forge
llvm-tools                11.0.1               hab3b255_0    conda-forge
llvmdev                   11.0.1               hab3b255_0    conda-forge
meson                     0.63.1             pyhd8ed1ab_0    conda-forge
ninja                     1.11.0               h2d74725_0    conda-forge
openssl                   3.0.5                h8ffe710_1    conda-forge
perl                      5.32.1.1        2_h57928b3_strawberry    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
python                    3.10.6          hcf16a7b_0_cpython    conda-forge
setuptools                65.3.0             pyhd8ed1ab_1    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tzdata                    2022c                h191b570_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
vc                        14.2                 hb210afc_7    conda-forge
vs2015_runtime            14.29.30139          h890b9b1_7    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zlib                      1.2.12               h8ffe710_2    conda-forge
```
